// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch_amalgamated.hpp"

#include "../Fraction.hpp"

// =====================
// Test the default constructor
// ---------------------

TEST_CASE("ex0", "[Default fraction]")
{
    Fraction f;

    SECTION("Default constructor") {
        REQUIRE(f.getNum()==0);
        REQUIRE(f.getDen()==1);
    }
}

// =====================
// Test the parameterized constructor
// ---------------------

TEST_CASE("ex1", "[Parameterized fraction]")
{
    Fraction f(3,7);

    SECTION("Parameterized constructor") {
        REQUIRE(f.getNum()==3);
        REQUIRE(f.getDen()==7);
    }
}

// =====================
// Test setters y getters
// ---------------------

TEST_CASE("ex2", "[Fraction's setters y getters]")
{
    Fraction f;

    SECTION("Setters y getters") {
        f.setNum(3);
        f.setDen(7);
        REQUIRE(f.getNum()==3);
        REQUIRE(f.getDen()==7);
    }
}

// =====================
// Test sum 
// ---------------------

TEST_CASE("ex3", "[Sum]")
{
    Fraction f(3, 4), g(2, 3), h;

    SECTION("Sum two fractions") {
        h = f.sum(g);
        REQUIRE(h.getNum() == 17);
        REQUIRE(h.getDen() == 12);
    }
}

